### ISSUE TITLE
Wrong Image Name when there is a bundle prefix.

### ISSUE THREAD

**Issue by ghost** [kevindelord/UIImage-Autoresize#4]
Hi kevindelord:

**Comment by ghost** [comment]
I found an issue : If there is a bundle prefix, such as [UIImage imageNamed:@"resource.bundle/camera.png"]. Image extension will append to "resource",  such as "resource-667h.bundle/camera.png".

Is there a way to fix it?

**Comment by ghost** [comment]
HaHa... I fix this bug by adding range options NSBackwardsSearch. It's works fine in my project.
@kevindelord

**Comment by kevindelord** [comment]
I'm sorry for the delay, I completely missed the email notification from GitHub, my apologies.

You are completely right, there is a problem if the original image contains another dot than the one for the extension. For example `buyButton.enabledMode.png` will become `buyButton-667h.enabledMode.png` which is wrong.

Using the range option NSBackwardsSearch sounds like a great idea !

Thanks

**Comment by kevindelord** [comment]
Here you go with the pull request: https://github.com/kevindelord/UIImage-Autoresize/pull/8

I will release a new version later this week.
