### ISSUE TITLE
iPhone 6 Plus, Zoomed mode is not detected

### ISSUE THREAD

**Issue by buildc0de** [kevindelord/UIImage-Autoresize#5]
Display Zoom can be configured in `Settings > Display & Brightness > Display Zoom`.

On iPhone 6 Plus:
- Zoomed mode renders at 3x, 375 × 667
- Standard mode renders at 3x, 414 × 736

(more info at http://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions)

Currently, UIImage-Autoresize looks for `"@3x"` images for both modes.

Will submit a PR shortly :smiley_cat:

**Comment by kevindelord** [comment]
Very interesting, thanks a lot for your support.
I have a small question regarding the iPhone 6.
Your link shows that this device also has a "zoomed" mode. Should we also update the code to react on this?

**Comment by buildc0de** [comment]
My pleasure :-) 

iPhone 6, Zoomed mode renders at 2x, 320 × 568, which is identical to iPhone 5/5s, so we are good here :-)

**Comment by kevindelord** [comment]
@waywalker merged! Thanks for your support.
I will release that as soon as with this complete new set of unit tests ;)
